language: java

jdk: oraclejdk8

before_install:
         - chmod +x gradlew

script:
 - gradle assemble
 - gradle check

notifications:
 email: false

language: python

python: "3.5"

install: "pip install pytest"

script: py.test